<a href="https://colab.research.google.com/github/LPSJ1/SemProject_MLEngine/blob/main/Rainfall_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
print(os.getcwd())
print(os.listdir())

/content
['.config', 'ken-rainfall-subnat-full.csv', 'sample_data']

In [ ]:
import pandas as pd
df = pd.read_csv('ken-rainfall-subnat-full.csv')

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 133245
Columns: 15

In [ ]:
df.dtypes

date          object
adm_level      int64
adm_id         int64
PCODE         object
n_pixels     float64
rfh          float64
rfh_avg      float64
r1h          float64
r1h_avg      float64
r3h          float64
r3h_avg      float64
rfq          float64
r1q          float64
r3q          float64
version       object
dtype: object

In [ ]:
df.isnull().sum()

date           0
adm_level      0
adm_id         0
PCODE          0
n_pixels       0
rfh            0
rfh_avg        0
r1h          162
r1h_avg      162
r3h          648
r3h_avg      648
rfq            0
r1q          162
r3q          648
version        0
dtype: int64

In [ ]:
first_15 = df.iloc[:15]
last_20 = df.iloc[-20:]
df_sample = pd.concat([first_15, last_20])
df_sample

,date,adm_level,adm_id,PCODE,n_pixels,rfh,rfh_avg,r1h,r1h_avg,r3h,r3h_avg,rfq,r1q,r3q,version
0,1981-01-01,1,51325,KE019,427.0,7.372365,15.759407,NaN,NaN,NaN,NaN,59.598840,NaN,NaN,final
1,1981-01-11,1,51325,KE019,427.0,4.325527,19.294770,NaN,NaN,NaN,NaN,38.384920,NaN,NaN,final
2,1981-01-21,1,51325,KE019,427.0,5.569087,16.265417,17.266980,51.319595,NaN,NaN,49.700817,39.536823,NaN,final
3,1981-02-01,1,51325,KE019,427.0,5.882904,12.719282,15.777517,48.279470,NaN,NaN,61.418427,38.997230,NaN,final
4,1981-02-11,1,51325,KE019,427.0,17.180328,18.768618,28.632318,47.753320,NaN,NaN,93.317700,63.753933,NaN,final
5,1981-02-21,1,51325,KE019,427.0,3.142857,11.827791,26.206089,43.315693,NaN,NaN,48.389336,64.587900,NaN,final
6,1981-03-01,1,51325,KE019,427.0,14.159250,29.220140,34.482437,59.816550,NaN,NaN,55.988228,60.914127,NaN,final
7,1981-03-11,1,51325,KE019,427.0,66.765810,28.629663,84.067920,69.677600,NaN,NaN,213.400310,119.269930,NaN,final
8,1981-03-21,1,51325,KE019,427.0,141.128800,41.624825,222.053860,99.474630,265.52692,194.10991,313.414150,217.329200,135.868130,final
9,1981-04-01,1,51325,KE019,427.0,105.707260,73.952380,313.601870,144.206860,363.86182,252.30289,140.220290,213.530300,143.357060,final
10,1981-04-11,1,51325,KE019,427.0,162.604220,71.159410,409.440280,186.736620,522.14050,304.16754,220.070270,216.150830,170.503190,final
11,1981-04-21,1,51325,KE019,427.0,42.850117,84.537240,311.161600,229.649020,559.42150,372.43936,53.441586,134.738080,149.539640,final
12,1981-05-01,1,51325,KE019,427.0,118.255270,68.002890,323.709600,223.699520,671.79390,427.72296,168.836150,143.729900,156.403500,final
13,1981-05-11,1,51325,KE019,427.0,93.201410,59.470490,254.306800,212.010620,747.81500,468.42484,152.319930,119.490370,159.014680,final
14,1981-05-21,1,51325,KE019,427.0,17.763466,44.923030,229.220150,172.396410,762.43560,501.52005,45.597122,132.032070,151.511400,final
133225,2026-02-21,2,68770,KE029151,42.0,119.666664,20.580952,313.976200,68.999210,496.40475,221.56984,487.341800,431.053530,221.302500,final
133226,2026-03-01,2,68770,KE029151,42.0,110.500000,37.393650,346.880950,84.453970,600.80960,229.56667,272.446470,393.365400,258.267550,final
133227,2026-03-11,2,68770,KE029151,42.0,84.309525,44.833332,314.476200,102.807940,589.07140,254.33492,179.216450,296.338300,229.075000,final
133228,2026-03-21,2,68770,KE029151,42.0,92.071430,57.824604,286.880950,140.051590,624.09520,280.01825,154.511800,201.225620,220.721020,final
133229,2026-04-01,2,68770,KE029151,42.0,46.142857,69.588100,222.523800,172.246030,664.76190,330.20000,68.567050,128.366090,199.809630,final
133230,2026-04-11,2,68770,KE029151,42.0,36.071430,70.042854,174.285700,197.455550,687.59520,372.51270,54.730637,88.555590,183.462770,final
133231,2026-04-21,2,68770,KE029151,42.0,120.500000,88.593650,202.714300,228.224610,803.57140,437.27540,134.090290,89.061910,182.820800,final
133232,2026-05-01,2,68770,KE029151,42.0,100.500000,77.160320,257.071400,235.796830,826.47620,492.49683,128.407490,108.835075,167.131960,final
133233,2026-05-11,2,68770,KE029151,42.0,50.833332,64.819840,271.833340,230.573800,760.59520,530.83730,79.967720,117.514480,142.878310,final
133234,2026-05-21,2,68770,KE029151,42.0,43.690475,57.700000,195.023800,199.680160,684.61900,567.95636,77.656260,97.725060,120.361534,final
133235,2026-06-01,2,68770,KE029151,42.0,25.619047,46.527780,120.142850,169.047620,599.73810,577.09045,59.422410,71.901500,103.890740,final
133236,2026-06-11,2,68770,KE029151,42.0,9.547619,45.723810,78.857150,149.951580,524.97614,577.98096,28.680060,54.118286,90.907970,final
133237,2026-06-21,2,68770,KE029151,42.0,19.047619,44.684128,54.214283,136.935710,451.95236,564.84045,48.401010,41.719086,80.189530,final
133238,2026-07-01,2,68770,KE029151,42.0,36.333332,40.559525,64.928570,130.967470,442.14282,535.81190,90.723800,51.430367,82.679920,final
133239,2026-07-11,2,68770,KE029151,42.0,45.761906,49.527780,101.142850,134.771420,451.83330,515.29680,93.093666,75.940310,87.802440,final
133240,2026-07-21,2,68770,KE029151,42.0,44.047620,59.717460,126.142850,149.804760,375.38095,486.42062,75.787310,84.715000,77.404350,final
133241,2026-08-01,2,68770,KE029151,42.0,85.000000,51.057144,174.809520,160.302380,359.88095,460.31744,160.550450,108.776130,78.415490,final
133242,2026-08-11,2,68770,KE029151,42.0,33.095238,56.205555,162.142850,166.980160,342.14285,451.70320,62.241470,97.187290,76.010605,final
133243,2026-08-21,2,68770,KE029151,42.0,27.428572,66.633330,145.523800,173.896030,325.88095,460.63650,45.270230,84.140380,71.059920,final
133244,2026-09-01,2,68770,KE029151,42.0,16.952381,49.257145,77.476200,172.096040,317.21430,463.36588,40.459890,46.571453,68.795425,prelim